ticket:6109: Merge changes from trunk: r.26010 - 26765
git-svn-id: http://source.icu-project.org/repos/icu/icu@26775 251d0590-4201-4cf1-90de-194747b24ca1

diff --git a/branches/eric/lenient_number_parsing/source/configure b/branches/eric/lenient_number_parsing/source/configure
--- a/branches/eric/lenient_number_parsing/source/configure
+++ b/branches/eric/lenient_number_parsing/source/configure
@@ -655,6 +655,7 @@ LAYOUT_TRUE
 ICUIO_TRUE
 EXTRAS_TRUE
 U_CHECK_UTF16_STRING
+U_CHECK_GNUC_UTF16_STRING
 U_SIZEOF_WCHAR_T
 U_HAVE_WCSCPY
 U_HAVE_WCHAR_H
@@ -673,6 +674,7 @@ U_HAVE_TZNAME
 U_TZSET
 U_HAVE_TZSET
 U_HAVE_POPEN
+U_HAVE_GCC_ATOMICS
 U_HAVE_PLACEMENT_NEW
 U_OVERRIDE_CXX_ALLOCATION
 U_HAVE_NAMESPACE
@@ -700,6 +702,7 @@ LIBCXXFLAGS
 LIBCFLAGS
 U_USE_GCC_VISIBILITY_ATTRIBUTE
 U_DEFAULT_SHOW_DRAFT
+UCLN_NO_AUTO_CLEANUP
 ENABLE_RELEASE
 ENABLE_DEBUG
 ENABLE_STATIC
@@ -790,6 +793,7 @@ enable_shared
 enable_static
 enable_debug
 enable_release
+enable_auto_cleanup
 enable_draft
 enable_renaming
 enable_tracing
@@ -1447,6 +1451,7 @@ Optional Features:
   --enable-static         build static libraries default=no
   --enable-debug          build debug libraries default=no
   --enable-release        build release libraries default=yes
+  --enable-auto-cleanup   enable auto cleanup of libraries default=no
   --enable-draft          enable draft APIs default=yes
   --enable-renaming       add a version suffix to symbols default=yes
   --enable-tracing        enable function and data tracing default=no
@@ -4110,19 +4115,16 @@ fi
             *) ;;
         esac
     elif test "$DEFAULT_64BIT" = "unknown"; then
-        { { $as_echo "$as_me:$LINENO: error: Unable to determine binary format." >&5
-$as_echo "$as_me: error: Unable to determine binary format." >&2;}
-   { (exit 1); exit 1; }; }
-        # cross compiling?
-        #BITS_GOT=unknown
-        #case "$BITS_REQ" in
-        #    64|64else32) BITS_OK=no
-        #    BITS_CHECK_32=yes
-        #    BITS_CHECK_64=yes
-        #    32) BITS_OK=no;;
-        #    nochange) ;;
-        #    *) ;;
-        #esac
+        # cross compiling.
+        BITS_GOT=unknown
+        case "$BITS_REQ" in
+            64|64else32) BITS_OK=no
+            BITS_CHECK_32=yes
+            BITS_CHECK_64=yes ;;
+            32) BITS_OK=no;;
+            nochange) ;;
+            *) ;;
+        esac
     fi
 
     { $as_echo "$as_me:$LINENO: result: $DEFAULT_64BIT" >&5
@@ -5012,6 +5014,82 @@ fi
 { $as_echo "$as_me:$LINENO: result: $enabled" >&5
 $as_echo "$enabled" >&6; }
 
+
+# Check whether to enable auto cleanup of libraries
+{ $as_echo "$as_me:$LINENO: checking whether to enable auto cleanup of libraries" >&5
+$as_echo_n "checking whether to enable auto cleanup of libraries... " >&6; }
+enabled=no
+UCLN_NO_AUTO_CLEANUP=1
+# Check whether --enable-auto-cleanup was given.
+if test "${enable_auto_cleanup+set}" = set; then
+  enableval=$enable_auto_cleanup;  case "${enableval}" in
+         yes) enabled=yes; UCLN_NO_AUTO_CLEANUP=0 ;;
+         *) ;;
+    esac
+fi
+
+{ $as_echo "$as_me:$LINENO: result: $enabled" >&5
+$as_echo "$enabled" >&6; }
+
+
+# MSVC floating-point option
+MSVC_RELEASE_FLAG=""
+if test $enabled = yes
+then
+    if test $icu_cv_host_frag = mh-cygwin-msvc
+    then
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #if defined _MSC_VER && _MSC_VER >= 1400
+    #else
+    Microsoft Visual C++ < 2005
+    #endif
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  MSVC_RELEASE_FLAG="/fp:precise"
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	MSVC_RELEASE_FLAG="/Op"
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+        CFLAGS="${CFLAGS} ${MSVC_RELEASE_FLAG}"
+        CXXFLAGS="${CXXFLAGS} ${MSVC_RELEASE_FLAG}"
+    fi
+fi
 
 # Check whether to enabled draft APIs
 { $as_echo "$as_me:$LINENO: checking whether to enable draft APIs" >&5
@@ -5983,20 +6061,9 @@ $as_echo "$ac_cv_func_pthread_mutex_lock" >&6; }
   case "${host}" in
   *-pc-cygwin*|*-pc-mingw*)
     # For gcc, the thread options are set by mh-mingw/mh-cygwin
+    # For msvc, the thread options are set by runConfigureICU
     ICU_USE_THREADS=1
-    if test "$ac_cv_c_compiler_gnu" = no; then
-      # We're using normal windows compilers. Threading is available.
-      ICU_USE_THREADS=1
-      if test $ENABLE_DEBUG = 1; then
-        # /MDd means 'compiles and links a debugable multithreaded program with DLL'
-        CFLAGS="${CFLAGS} /MDd"
-        CXXFLAGS="${CXXFLAGS} /MDd"
-      else
-        # /MD means 'compiles and links a multithreaded program with DLL'
-        CFLAGS="${CFLAGS} /MD"
-        CXXFLAGS="${CXXFLAGS} /MD"
-      fi
-    fi ;;
+    ;;
   *-*-hpux*)
     # Add -mt because it does several nice things on newer compilers.
     case "${icu_cv_host_frag}" in
@@ -6006,6 +6073,13 @@ $as_echo "$ac_cv_func_pthread_mutex_lock" >&6; }
         if test x"`${CXX} ${CXXFLAGS} 2>&1`" != x""; then
            CXXFLAGS="${OLD_CXXFLAGS}"
        fi
+      ;;
+    esac
+    ;;
+  *-*-solaris*)
+    case "${icu_cv_host_frag}" in
+      mh-solaris)
+           LIBS="${LIBS} -mt"
       ;;
     esac
     ;;
@@ -7810,6 +7884,75 @@ $as_echo "$ac_cv_override_placement_new_ok" >&6; }
     fi
 fi
 
+
+
+# gcc atomic built-in functions check
+# AC_TRY_LINK([], [int foo, bar; bar = __sync_val_compare_and_swap(&foo, 0, 1);],,
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+{ $as_echo "$as_me:$LINENO: checking for gcc atomic functions" >&5
+$as_echo_n "checking for gcc atomic functions... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+        void *p;
+        int   i;
+
+int
+main ()
+{
+
+        __sync_fetch_and_add(&i, 1);
+        __sync_fetch_and_sub(&i, 1);
+        __sync_val_compare_and_swap(&p, 0, 0);
+
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then
+  U_HAVE_GCC_ATOMICS=1; { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	U_HAVE_GCC_ATOMICS=0; { $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+fi
+
+rm -rf conftest.dSYM
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
 
 
 ac_ext=c
@@ -9976,6 +10119,7 @@ fi
 $as_echo_n "checking for UTF-16 string literal support... " >&6; }
 U_CHECK_UTF16_STRING=1
 CHECK_UTF16_STRING_RESULT="unknown"
+
 case "${host}" in
 *-*-aix*|powerpc64-*-linux*)
     if test "$ac_cv_c_compiler_gnu" = no; then
@@ -10110,6 +10254,78 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 *)
     ;;
 esac
+
+# GCC >= 4.4 supports UTF16 string literals. The CFLAGS and CXXFLAGS may change in the future.
+# Since we have to use a different standard, if strict is enable, don't enable UTF16 string literals.
+U_CHECK_GNUC_UTF16_STRING=0
+if test "$ac_use_strict_options" = no && test "$CHECK_UTF16_STRING_RESULT" = "unknown"; then
+    if test "$ac_cv_c_compiler_gnu" = yes; then
+        OLD_CFLAGS="${CFLAGS}"
+        OLD_CXXFLAGS="${CXXFLAGS}"
+        CFLAGS="${CFLAGS} -std=gnu99 -D_GCC_"
+        CXXFLAGS="${CXXFLAGS} -std=c++0x"
+        cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 4)
+#ifdef _GCC_
+typedef __CHAR16_TYPE__ char16_t;
+#endif
+char16_t test[] = u"This is a UTF16 literal string.";
+#else
+GCC IS TOO OLD!
+#endif
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  U_CHECK_UTF16_STRING=1
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	U_CHECK_UTF16_STRING=0
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+        if test "$U_CHECK_UTF16_STRING" = 1; then
+            CHECK_UTF16_STRING_RESULT="available";
+            U_CHECK_GNUC_UTF16_STRING=1
+        else
+            CFLAGS="${OLD_CFLAGS}"
+            CXXFLAGS="${OLD_CXXFLAGS}"
+        fi
+    fi
+fi
+
+
 { $as_echo "$as_me:$LINENO: result: $CHECK_UTF16_STRING_RESULT" >&5
 $as_echo "$CHECK_UTF16_STRING_RESULT" >&6; }
 
@@ -10237,9 +10453,11 @@ case "$datapackaging" in
     fi
     datapackaging_howfound="$datapackaging_msg_set"
     ;;
-#    static)
-#	DATA_PACKAGING_MODE=static
-#	;;
+    static)
+    DATA_PACKAGING_MODE=static
+    datapackaging_msg="ICU data will be stored in a static library."
+    datapackaging_howfound="$datapackaging_msg_set"
+    ;;
 esac
 
 
